[mypy]
# Path to Klipper source directory, replace with your actual Klipper path
mypy_path = c:/GitHub/klipper/klippy
namespace_packages = True
explicit_package_bases = True
# Explicitly list the files to check
files = ldc1612_ng.py, probe_eddy_ng.py
